### ISSUE TITLE
Some questions about data

### ISSUE THREAD

**Issue by qiuqiu746** [frenkowski/Raman_Spectroscopy_and_Deep_Learning#1]
Hello, thank you very much for sharing your results, I am very interested in your research direction. I ran your code but there are some problems, I would like to ask you for advice, 

[Errno 2] No such file or directory: '/content/drive/MyDrive/Deep_Learning_for_Bacteria_Identification_using_Raman_Spectroscopy-main/dataset/bacteria/X_reference.npy

I don't know how to modify it, could you please share X_reference.npy? Thank you very much, looking forward to your reply.

**Comment by dvdmarchetti** [comment]
Hi!
Thanks for the intrest in our research.

The dataset is available in [this Dropbox folder](https://www.dropbox.com/sh/gmgduvzyl5tken6/AABtSWXWPjoUBkKyC2e7Ag6Da?dl=0).
Once downloaded, you have to place it into the `dataset/bacteria` folder of this repository's clone.
